apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: blip
spec:
  version: ${TAG}
  homepage: https://github.com/project-unbounded/blip
  shortDescription: Blip SSH key management
  description: |
    Signs your local SSH public key with the Blip SSH CA and generates
    VirtualMachinePool manifests for the Blip VM pool.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/project-unbounded/blip/releases/download/${TAG}/kubectl-blip_linux_amd64.tar.gz
      sha256: ${sha_linux_amd64}
      bin: kubectl-blip
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/project-unbounded/blip/releases/download/${TAG}/kubectl-blip_linux_arm64.tar.gz
      sha256: ${sha_linux_arm64}
      bin: kubectl-blip
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/project-unbounded/blip/releases/download/${TAG}/kubectl-blip_darwin_amd64.tar.gz
      sha256: ${sha_darwin_amd64}
      bin: kubectl-blip
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/project-unbounded/blip/releases/download/${TAG}/kubectl-blip_darwin_arm64.tar.gz
      sha256: ${sha_darwin_arm64}
      bin: kubectl-blip
